### ISSUE TITLE
assert len(matches) == len(pipe_lora_list) * 2

### ISSUE THREAD

**Issue by donaldssh** [Young98CN/LoRA_Composer#2]
Hi, thank you for your work.

I was trying to replicate the experiments following the instructions on the [readme](https://github.com/Young98CN/LoRA_Composer?tab=readme-ov-file#runner-some-instances-in-the-paper).
However, the code crashes when running `bash scripts/lora_composer_scripts/paper_result_scripts/lora_composer_real.sh`

For each experiment in lora_composer_real.sh, it crashes with the following error:
```
assert len(matches) == len(pipe_lora_list) * 2, f"Check the matching relationship between{matches} and the number of LoRAs in the {args.combined_model_root} directory"
```

Do you know what could be the reason?

**Comment by Young98CN** [comment]
Have you run[ this code](https://github.com/Young98CN/LoRA_Composer/blob/main/README.md#:~:text=Merge%20the%20LoRA,merge_EDLoRA/link_lora2folder.py)(Merge the LoRA with the base model in the README) ? Before running the model, you need to link the weights to a unified format folder, otherwise the error you mentioned will occur.

**Comment by donaldssh** [comment]
I confirm that it works, thank you.
