### ISSUE TITLE
Every multi-concept out-of-memory on 24GB RTX 4090,when bash scripts/lora_composer_scripts/paper_result_scripts/lora_composer_real.sh

### ISSUE THREAD

**Issue by JohnsonXi** [Young98CN/LoRA_Composer#4]
Have you considered improving computational efficiency? A single merged ED LORA model takes up 3.5GB of memory. With multiple concept combinations, along with Stable Diffusion, T2I, and other models, the total memory usage on my 24GB RTX 4090 GPU ends up exceeding the available memory, causing out-of-memory issues.

**Comment by Young98CN** [comment]
Actually, I try to improve computational efficiency on [optimization branch](https://github.com/Young98CN/LoRA_Composer/tree/optimized_version) (both in GPU memory and storage). It need not merge ED LoRA during the inference process, but it may be can not run on 24G memory upon our original real concepts config (animate config in my device can run, about 23.9GB GPU memory). If you want to run real config, you can try to reduce the [resolution](https://github.com/Young98CN/LoRA_Composer/blob/41616f6068c5e177db265f6e938026fcd0c89a63/inference/region_lora_sample.py#L375-L376)(like 1024*512)  and attention resolution.

**Comment by JohnsonXi** [comment]
<img width="331" alt="image" src="https://github.com/user-attachments/assets/2a80dfe9-3446-4891-b6ce-61c9aa10d97b">
Thank you for your efforts! As shown in the image, when I try to modify the resolution of the "real" input to [1024,512], the following computation error occurs. The support for modifying the resolution does not seem to be very good.
<img width="724" alt="image" src="https://github.com/user-attachments/assets/d2727c55-db95-40c6-acfa-82f20514e228">

**Comment by Young98CN** [comment]
The attn_resolution needs to change with the width and height, you need to adjust it to [16, 32]

**Comment by JohnsonXi** [comment]
<img width="728" alt="image" src="https://github.com/user-attachments/assets/adab26e7-8965-4d1a-8604-69725cb584a8">
Same issues.
<img width="333" alt="image" src="https://github.com/user-attachments/assets/715055a9-fc53-48b7-82ba-549bf24af77d">

**Comment by Young98CN** [comment]
Did you modify the config? If you modify the resolution, you should modify all of hight of the [_region_ ](https://github.com/Young98CN/LoRA_Composer/blob/a48a5a597f7a1745825d8971955fc4d4d4c39fa8/scripts/lora_composer_scripts/paper_result_scripts/lora_composer_real.sh#L15)in the config (for example [10, 0, 512, 350], reduce the height from 767-->512, it should small than hight which you setting in the code). In addition, when you change the resolution, the condition will not available, scripts (like [this](https://github.com/Young98CN/LoRA_Composer/blob/a48a5a597f7a1745825d8971955fc4d4d4c39fa8/scripts/lora_composer_scripts/paper_result_scripts/lora_composer_real.sh#L184)) with identifiers in config will not work, because these conditions are strongly related to resolution (canny or human pose).

**Comment by JohnsonXi** [comment]
Doing it this way is quite inconvenient. It seems that if I want to reproduce the results, I will still need a machine with more GPU memory.

**Comment by JohnsonXi** [comment]
It would be even better if the README had a table showing the GPU memory requirements and runtime for different settings. Thank you for your patient guidance, and best wishes for your research!
